---
  
- name: Variable output testing
  hosts: localhost
  vars:
   # - #username: vishal
      #password: soni
  gather_facts: True
  become: False
  tasks:

    - name: Debug variables to view contents
      debug:
        msg: "{{ item }} is in variable list"
      with_items:
        - "{{ username }}"
        - "{{ password }}"
